Fix functional job failure in gate
Currently functional tests are failing because of the following error
during installation kicked by tox.
  error: [Errno 13] Permission denied: 'storlets.egg-info'

This patch makes sure that egg-info directory is removed after engine
installation, so that tox won't fail with the permission error.

Change-Id: I3842a758748450da98f9b4e320eb4a6f27c98bca